### ISSUE TITLE
Help.md problems with prove6 & test files

### ISSUE THREAD

**Issue by masukomi** [exercism/raku#546]
the instructions in `Help.md` say 

> Running the tests
> 
> You can run the test suite for the exercise by executing the command
> `prove6 .` in the exercise directory.

which is accurate, but there are two problems

1. the period is easy to miss, and can be interpreted as the ending of the prior sentence. 
2. `prove6` shouldn't need to be passed a `.` because 

> If no files or directories are supplied, prove6 looks for all files matching the pattern `t/*.t`.

Building on this, after reading [the current Raku documentation about writing tests](https://docs.raku.org/language/testing), the convention appears to be to use the `.t` extension on test files, not `.rakutest`

## Suggested fixes
(from a newb) 
### "Real" fix
change all the `.rakutest` extensions to `.t` 

### Quickie stopgap: 

Change `Help.md` to put the command to be run on a line by itself like the example below. Maybe add a sentence noting that the period is important. 

```
...by executing the following command in the exercise directory.

\```
$ prove6 .
\```
```
(👆sorry about the `\` I can't figure out how to escape triple backticks in a codeblock without it showing up)

Without this fix, you can end up like me; running `prove6` without it and getting an error message that isn't even remotely helpful to someone who doesn't know what it's talking about with `input 't'`  without going off and doing a lot of investigating. 

```
❯ prove6
Invalid input 't'
<stack trace here>
```

even after reading the testing docs and the `prove6` docs i'm still not sure how it understands to run the `.rakutest` files when you give it `.` or `--lib .`

**Comment by m-dango** [comment]
Hi @masukomi

Both `.rakutest` and `.t` are supported, `.rakutest` being the newer one, to go alongside `.raku` and `.rakumod`:
https://github.com/Raku/problem-solving/blob/master/solutions/language/Path-to-Raku.md#extensions
https://github.com/Leont/app-prove6/blob/master/Changes#L15

The issue you're encountering is that the default behavior of prove6 expects the tests to be in a directory called `t`, but this is not the case due to reasons that were applicable for older versions of Exercism.

The ideal solution here would be to restructure the exercises to use `lib` and `t` directories for modules and tests respectively. In the meantime I can tweak the docs for clarity.

**Comment by m-dango** [comment]
I've opened pull request #547 for making changes to the docs. I have also noticed that the latest version of prove6 has addressed the `Invalid input` error, which should likely be included with future versions of Rakudo Star.

**Comment by masukomi** [comment]
Thanks @m-dango  that's much clearer. :D
